package ui;

import java.awt.Component;
import java.awt.PopupMenu;
import javax.swing.JLabel;
import javax.swing.JPanel;
import ui.Dangnhap;
import ui.ThongTinChuyenTau;
import ui.ThongTinNV;
import ui.ThongTinTau;
import ui.ThongTinVe;
import ui.TimKiemNV;
import ui.TimKiemVe;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Student
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_chucnang = new javax.swing.JPanel();
        lbl_bg = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Home = new javax.swing.JMenu();
        NV = new javax.swing.JMenu();
        timNV = new javax.swing.JMenuItem();
        ThongTinNV = new javax.swing.JMenuItem();
        Ve = new javax.swing.JMenu();
        DatVe = new javax.swing.JMenuItem();
        ThongTInVe = new javax.swing.JMenuItem();
        Tau = new javax.swing.JMenu();
        ThongTinTAu = new javax.swing.JMenuItem();
        ChuyenTau = new javax.swing.JMenu();
        ThongTInChuyenTau = new javax.swing.JMenuItem();
        Tk = new javax.swing.JMenu();
        DangNhap = new javax.swing.JMenuItem();
        Dangxuat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1150, 600));

        panel_chucnang.setLayout(new java.awt.CardLayout());

        lbl_bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dangnhapimg.jpg"))); // NOI18N
        panel_chucnang.add(lbl_bg, "card2");

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jMenuBar1.setMargin(new java.awt.Insets(0, 0, 0, 30));

        Home.setText("Home");
        Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomeMouseClicked(evt);
            }
        });
        Home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeActionPerformed(evt);
            }
        });
        jMenuBar1.add(Home);

        NV.setText("Nhân viên");
        NV.setMargin(new java.awt.Insets(10, 10, 10, 10));
        NV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                NVMouseEntered(evt);
            }
        });
        NV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NVActionPerformed(evt);
            }
        });

        timNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/magnifier.png"))); // NOI18N
        timNV.setText("Tìm nhân viên");
        timNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timNVMouseClicked(evt);
            }
        });
        timNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timNVActionPerformed(evt);
            }
        });
        NV.add(timNV);

        ThongTinNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/man.png"))); // NOI18N
        ThongTinNV.setText("Thông tin nhân viên");
        ThongTinNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongTinNVActionPerformed(evt);
            }
        });
        NV.add(ThongTinNV);

        jMenuBar1.add(NV);

        Ve.setText("Vé");

        DatVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ticket.png"))); // NOI18N
        DatVe.setText("Đặt vé");
        DatVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatVeActionPerformed(evt);
            }
        });
        Ve.add(DatVe);

        ThongTInVe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/tickets.png"))); // NOI18N
        ThongTInVe.setText("Thông tin vé");
        ThongTInVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongTInVeActionPerformed(evt);
            }
        });
        Ve.add(ThongTInVe);

        jMenuBar1.add(Ve);

        Tau.setText("Tàu");
        Tau.setDoubleBuffered(true);

        ThongTinTAu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/train1.png"))); // NOI18N
        ThongTinTAu.setText("Thông tin tàu");
        ThongTinTAu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongTinTAuActionPerformed(evt);
            }
        });
        Tau.add(ThongTinTAu);

        jMenuBar1.add(Tau);

        ChuyenTau.setText("Chuyến Tàu");

        ThongTInChuyenTau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/train.png"))); // NOI18N
        ThongTInChuyenTau.setText("Thông tin chuyến tàu");
        ThongTInChuyenTau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThongTInChuyenTauActionPerformed(evt);
            }
        });
        ChuyenTau.add(ThongTInChuyenTau);

        jMenuBar1.add(ChuyenTau);

        Tk.setText("Tài khoản");

        DangNhap.setText("Đăng nhập");
        DangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangNhapActionPerformed(evt);
            }
        });
        Tk.add(DangNhap);

        Dangxuat.setText("Đăng xuất");
        Dangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DangxuatActionPerformed(evt);
            }
        });
        Tk.add(Dangxuat);

        jMenuBar1.add(Tk);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_chucnang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_chucnang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_chucnang.getAccessibleContext().setAccessibleName("Panel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NVMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_NVMouseEntered

    private void ThongTinNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongTinNVActionPerformed
        panel_chucnang.removeAll();
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
        ThongTinNV thongTinNV = new ThongTinNV(); // Create an instance of ThongTinNV
        panel_chucnang.add(thongTinNV);
        thongTinNV.setVisible(true);
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
    }//GEN-LAST:event_ThongTinNVActionPerformed

    private void DatVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatVeActionPerformed
        panel_chucnang.removeAll();
        panel_chucnang.repaint();
        panel_chucnang.revalidate(); 
        TimKiemVe timVe = new TimKiemVe(); // Create an instance of ThongTinNV
        panel_chucnang.add(timVe);
        timVe.setVisible(true);
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
    }//GEN-LAST:event_DatVeActionPerformed

    private void DangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangxuatActionPerformed
        this.dispose();
    }//GEN-LAST:event_DangxuatActionPerformed

    private void ThongTInVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongTInVeActionPerformed
        panel_chucnang.removeAll();
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
        ThongTinVe thongTinVe = new ThongTinVe(); // Create an instance of ThongTinNV
        panel_chucnang.add(thongTinVe);
        thongTinVe.setVisible(true);
        panel_chucnang.repaint();
        panel_chucnang.revalidate();           
    }//GEN-LAST:event_ThongTInVeActionPerformed

    private void HomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeActionPerformed
     
    }//GEN-LAST:event_HomeActionPerformed

    private void DangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DangNhapActionPerformed
        panel_chucnang.removeAll();
        panel_chucnang.repaint();
        panel_chucnang.revalidate(); 
        Dangnhap dangnhap = new Dangnhap();
        panel_chucnang.add(dangnhap);
        dangnhap.setVisible(true);
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
    }//GEN-LAST:event_DangNhapActionPerformed

    private void ThongTinTAuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongTinTAuActionPerformed
        panel_chucnang.removeAll();
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
        ThongTinTau thongTintau = new ThongTinTau(); // Create an instance of ThongTinNV
        panel_chucnang.add(thongTintau);
        thongTintau.setVisible(true);
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
    }//GEN-LAST:event_ThongTinTAuActionPerformed

    private void ThongTInChuyenTauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThongTInChuyenTauActionPerformed
        panel_chucnang.removeAll();
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
        ThongTinChuyenTau thongtinchuyentau = new ThongTinChuyenTau();
        panel_chucnang.add(thongtinchuyentau);
        thongtinchuyentau.setVisible(true);
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
    }//GEN-LAST:event_ThongTInChuyenTauActionPerformed

    private void HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomeMouseClicked
        panel_chucnang.removeAll();
        panel_chucnang.add(lbl_bg);
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
    }//GEN-LAST:event_HomeMouseClicked

    private void NVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NVActionPerformed

    private void timNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timNVActionPerformed
        panel_chucnang.removeAll();
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
        TimKiemNV TimKiemNV = new TimKiemNV(); // Create an instance of ThongTinNV
        panel_chucnang.add(TimKiemNV);
        TimKiemNV.setVisible(true);
        panel_chucnang.repaint();
        panel_chucnang.revalidate();
    }//GEN-LAST:event_timNVActionPerformed

    private void timNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timNVMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_timNVMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ChuyenTau;
    private javax.swing.JMenuItem DangNhap;
    private javax.swing.JMenuItem Dangxuat;
    private javax.swing.JMenuItem DatVe;
    private javax.swing.JMenu Home;
    private javax.swing.JMenu NV;
    private javax.swing.JMenu Tau;
    private javax.swing.JMenuItem ThongTInChuyenTau;
    private javax.swing.JMenuItem ThongTInVe;
    private javax.swing.JMenuItem ThongTinNV;
    private javax.swing.JMenuItem ThongTinTAu;
    private javax.swing.JMenu Tk;
    private javax.swing.JMenu Ve;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbl_bg;
    private javax.swing.JPanel panel_chucnang;
    private javax.swing.JMenuItem timNV;
    // End of variables declaration//GEN-END:variables

    private PopupMenu JLabel(String string) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
