/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.microsoft.sqlserver.jdbc.SQLServerDriver;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
/**
 *
 * @author Tei
 */
public class ThongTinNV extends javax.swing.JPanel {
        Connection conn = null;
        private static final String url = "jdbc:sqlserver://localhost\\Tei-Laptop:1433;databaseName=BanVeTau;integratedSecurity=false;encrypt=false;trustServerCertificate=true;";
        private static final String username = "tei";
        private static final String password = "29032004";
        PreparedStatement pst = null;
        ResultSet rs = null;
        int i,q, id, deleteItem;
        JPanel panel = new JPanel();     
        // Set the table model, add columns, etc.
    /**
     * Creates new form NewJPanel
     */
    public ThongTinNV() {
        this.tbl_DSNV = new JScrollPane(DSNV);
        initComponents();
        DSNV = new JTable();
        panel.add(tbl_DSNV);
        this.add(panel);
    }
    public void SuaDB() throws ClassNotFoundException, SQLException{
    try {
        Class.forName("com.mssql.jdbc.Driver");
        conn = DriverManager.getConnection("jdbc:sqlserver://localhost\\Tei-Laptop:1433;databaseName=BanVeTau;integratedSecurity=false;encrypt=false;trustServerCertificate=true;", "tei", "29032004");
        pst = conn.prepareStatement("SELECT * FROM dbo.NhanVien");
        rs = pst.executeQuery();
        ResultSetMetaData stData = rs.getMetaData();
        q = stData.getColumnCount();
        DefaultTableModel model = (DefaultTableModel)DSNV.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Vector columnData = new Vector();
                System.out.println(rs.getString("MaNV"));
                columnData.add(rs.getString("MaNV"));
                columnData.add(rs.getString("HoTen"));
                columnData.add(rs.getString("CCCD"));
                columnData.add(rs.getString("GioiTinh"));
                columnData.add(rs.getString("SDT"));
                columnData.add(rs.getString("Email"));
                columnData.add(rs.getString("NamSinh"));
                columnData.add(rs.getString("TrinhDo"));
                columnData.add(rs.getString("MaNhaGa"));
            model.addRow(columnData);
        }
            DSNV.revalidate();
            DSNV.repaint();   
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Header = new javax.swing.JLabel();
        panel_thongtin = new javax.swing.JPanel();
        lbl_MaNV = new javax.swing.JLabel();
        lbl_hoTen = new javax.swing.JLabel();
        lbl_CCCD = new javax.swing.JLabel();
        lbl_NgaySinh = new javax.swing.JLabel();
        txt_NgaySinh = new javax.swing.JTextField();
        txt_CCCD = new javax.swing.JTextField();
        txt_HoTen = new javax.swing.JTextField();
        txt_MaNV = new javax.swing.JTextField();
        lbl_GioiTinh = new javax.swing.JLabel();
        lbl_Email = new javax.swing.JLabel();
        lbl_SDT = new javax.swing.JLabel();
        lbl_MaNhaG = new javax.swing.JLabel();
        txt_MaNhaGa = new javax.swing.JTextField();
        txt_SDT = new javax.swing.JTextField();
        txt_Email = new javax.swing.JTextField();
        cbb_GioiTinh = new javax.swing.JComboBox<>();
        lbl_TrinhDO = new javax.swing.JLabel();
        cbb_TrinhDO = new javax.swing.JComboBox<>();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        layout_table = new javax.swing.JPanel();
        tbl_DSNV = new javax.swing.JScrollPane();
        DSNV = new javax.swing.JTable();

        lbl_Header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Header.setText("THÔNG TIN NHÂN VIÊN");

        panel_thongtin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_MaNV.setText("Mã nhân viên:");
        panel_thongtin.add(lbl_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lbl_hoTen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_hoTen.setText("Họ tên:");
        panel_thongtin.add(lbl_hoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 51, -1, -1));

        lbl_CCCD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_CCCD.setText("CCCD:");
        panel_thongtin.add(lbl_CCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 96, -1, -1));

        lbl_NgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NgaySinh.setText("Ngày sinh");
        panel_thongtin.add(lbl_NgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(38, 141, -1, -1));

        txt_NgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel_thongtin.add(txt_NgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 142, 173, -1));

        txt_CCCD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel_thongtin.add(txt_CCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 97, 173, -1));

        txt_HoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel_thongtin.add(txt_HoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 52, 173, -1));

        txt_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel_thongtin.add(txt_MaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 7, 173, -1));

        lbl_GioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_GioiTinh.setText("Giới tính:");
        panel_thongtin.add(lbl_GioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 7, -1, -1));

        lbl_Email.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_Email.setText("Email:");
        panel_thongtin.add(lbl_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, -1, -1));

        lbl_SDT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_SDT.setText("Số điện thoại:");
        panel_thongtin.add(lbl_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 95, -1, -1));

        lbl_MaNhaG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_MaNhaG.setText("Mã nhà ga:");
        lbl_MaNhaG.setToolTipText("");
        panel_thongtin.add(lbl_MaNhaG, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 140, -1, -1));

        txt_MaNhaGa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel_thongtin.add(txt_MaNhaGa, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 141, 173, -1));

        txt_SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel_thongtin.add(txt_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 96, 173, -1));

        txt_Email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        panel_thongtin.add(txt_Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 51, 173, -1));

        cbb_GioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbb_GioiTinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nam", "Nữ" }));
        panel_thongtin.add(cbb_GioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 6, 173, -1));

        lbl_TrinhDO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TrinhDO.setText("Trình độ:");
        panel_thongtin.add(lbl_TrinhDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 6, -1, -1));

        cbb_TrinhDO.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbb_TrinhDO.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đại học", "Cử nhân", "Cao đẳng" }));
        panel_thongtin.add(cbb_TrinhDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 7, 172, -1));

        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });
        panel_thongtin.add(btn_Them, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 45, 120, -1));

        btn_Sua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });
        panel_thongtin.add(btn_Sua, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 89, 120, -1));

        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Xoa.setText("Xóa");
        panel_thongtin.add(btn_Xoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(671, 133, 120, -1));

        DSNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã nhân viên", "Họ tên", "CCCD", "Giới tính", "Số điện thoại", "Email", "Ngày sinh", "Trình độ", "Mã nhà ga"
            }
        ));
        DSNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DSNVMouseClicked(evt);
            }
        });
        tbl_DSNV.setViewportView(DSNV);

        javax.swing.GroupLayout layout_tableLayout = new javax.swing.GroupLayout(layout_table);
        layout_table.setLayout(layout_tableLayout);
        layout_tableLayout.setHorizontalGroup(
            layout_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbl_DSNV, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout_tableLayout.setVerticalGroup(
            layout_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout_tableLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbl_DSNV, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(lbl_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(layout_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_thongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_thongtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layout_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
       
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        try {
        conn = DriverManager.getConnection(url ,username, password);
        pst = conn.prepareStatement("UPDATE dbo.NhanVien SET HoTen = ?, CCCD = ?, GioiTinh = ?, SDT = ?, Email = ?, NamSinh = ?, TrinhDo = ?, MaNhaGa = ? WHERE MaNV = ?");
        pst.setString(1, txt_MaNV.getText());
        pst.setString(2, txt_HoTen.getText());
        pst.setString(3, txt_CCCD.getText());
        pst.setString(4, (String) cbb_GioiTinh.getSelectedItem());
        pst.setString(5, txt_SDT.getText());
        pst.setString(6, txt_Email.getText());
        pst.setString(7, txt_NgaySinh.getText());
        pst.setString(8, (String) cbb_TrinhDO.getSelectedItem());
        pst.setString(9, txt_MaNhaGa.getText());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Sửa thành công");
        SuaDB();
    } catch (SQLException ex) {
    if (ex.getSQLState().equals("23000")) {
        JOptionPane.showMessageDialog(this, "Data already exists");
    } else {
        java.util.logging.Logger.getLogger(ThongTinTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
} catch (ClassNotFoundException ex) {
    java.util.logging.Logger.getLogger(ThongTinTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void DSNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DSNVMouseClicked
        DefaultTableModel model = (DefaultTableModel)DSNV.getModel();
        int indexRow = DSNV.getSelectedRow();
        txt_MaNV.setText(model.getValueAt(indexRow, 1).toString());
        txt_HoTen.setText(model.getValueAt(indexRow, 2).toString());
        txt_CCCD.setText(model.getValueAt(indexRow, 3).toString());
        cbb_GioiTinh.setSelectedItem(model.getValueAt(indexRow, 4).toString());
        txt_SDT.setText(model.getValueAt(indexRow, 5).toString());
        txt_Email.setText(model.getValueAt(indexRow, 6).toString());
        txt_NgaySinh.setText(model.getValueAt(indexRow, 7).toString());
        cbb_TrinhDO.setSelectedItem(model.getValueAt(indexRow, 8).toString());
        txt_MaNhaGa.setText(model.getValueAt(indexRow, 9).toString());
    }//GEN-LAST:event_DSNVMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DSNV;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JComboBox<String> cbb_GioiTinh;
    private javax.swing.JComboBox<String> cbb_TrinhDO;
    private javax.swing.JPanel layout_table;
    private javax.swing.JLabel lbl_CCCD;
    private javax.swing.JLabel lbl_Email;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_Header;
    private javax.swing.JLabel lbl_MaNV;
    private javax.swing.JLabel lbl_MaNhaG;
    private javax.swing.JLabel lbl_NgaySinh;
    private javax.swing.JLabel lbl_SDT;
    private javax.swing.JLabel lbl_TrinhDO;
    private javax.swing.JLabel lbl_hoTen;
    private javax.swing.JPanel panel_thongtin;
    private javax.swing.JScrollPane tbl_DSNV;
    private javax.swing.JTextField txt_CCCD;
    private javax.swing.JTextField txt_Email;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_MaNhaGa;
    private javax.swing.JTextField txt_NgaySinh;
    private javax.swing.JTextField txt_SDT;
    // End of variables declaration//GEN-END:variables

}
