/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.microsoft.sqlserver.jdbc.SQLServerDriver;
/**
 *
 * @author Tei
 */
public class ThongTinVe extends javax.swing.JPanel {
    Connection conn = null;
        private static final String url = "jdbc:sqlserver://localhost\\Tei-Laptop:1433;databaseName=BanVeTau;integratedSecurity=false;encrypt=false;trustServerCertificate=true;";
        private static final String username = "tei";
        private static final String password = "29032004";
        PreparedStatement pst = null;
        ResultSet rs = null;
        int i,q, id, deleteItem;
    /**
     * Creates new form NewJPanel
     */
    public ThongTinVe() {
        initComponents();
    }
    public void SuaDB() throws ClassNotFoundException, SQLException{
        try {
        Class.forName("com.mssql.jdbc.Driver");
        conn = DriverManager.getConnection(url,username,password);  
        pst = conn.prepareStatement("Select * from dbo.Ve");
        rs = pst.executeQuery();
        ResultSetMetaData stData = rs.getMetaData();
        q = stData.getColumnCount();
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Vector columnData = new Vector();
                for(i = 1;i<=q;i++){
                columnData.add(rs.getString("MaVe"));
                columnData.add(rs.getString("TenVe"));
                columnData.add(rs.getString("LoaiVe"));
                columnData.add(rs.getString("NgayDi"));
                columnData.add(rs.getString("NgayVe"));
                columnData.add(rs.getString("MaKH"));
                columnData.add(rs.getString("MaNV"));
                columnData.add(rs.getString("MaChuyenTau"));
                }
            model.addRow(columnData);
        }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_Header = new javax.swing.JLabel();
        layout_thongtin = new javax.swing.JPanel();
        lbl_MaVe = new javax.swing.JLabel();
        lbl_MaChuyenTau = new javax.swing.JLabel();
        txt_MaChuyenTau = new javax.swing.JTextField();
        txt_MaVe = new javax.swing.JTextField();
        lbl_MaKH = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        cbb_LoaiVe = new javax.swing.JComboBox<>();
        lbl_LoaiVe = new javax.swing.JLabel();
        btn_Xoa = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        lbl_MaNV = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        lbl_TenVe = new javax.swing.JLabel();
        lbl_NgayDI = new javax.swing.JLabel();
        lbl_NgayVe = new javax.swing.JLabel();
        txt_TenVe = new javax.swing.JTextField();
        txt_NgayDi = new javax.swing.JTextField();
        txt_NgayVe = new javax.swing.JTextField();
        btn_print = new javax.swing.JButton();
        layout_table = new javax.swing.JPanel();
        tbl_DSNV = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        lbl_Header.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl_Header.setText("THÔNG TIN VÉ");

        lbl_MaVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_MaVe.setText("Mã vé:");

        lbl_MaChuyenTau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_MaChuyenTau.setText("Mã chuyến tàu:");

        txt_MaChuyenTau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txt_MaVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl_MaKH.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_MaKH.setText("Mã khách hàng:");

        txt_MaKH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbb_LoaiVe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbb_LoaiVe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Loại 1", "Loại 2" }));
        cbb_LoaiVe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_LoaiVeActionPerformed(evt);
            }
        });

        lbl_LoaiVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_LoaiVe.setText("Loại vé:");

        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Xoa.setText("Xóa");

        btn_Sua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        lbl_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_MaNV.setText("Mã nhân viên:");

        txt_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        lbl_TenVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TenVe.setText("Tên vé:");

        lbl_NgayDI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NgayDI.setText("Ngày đi:");

        lbl_NgayVe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_NgayVe.setText("Ngày về:");

        btn_print.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btn_print.setText("In");

        javax.swing.GroupLayout layout_thongtinLayout = new javax.swing.GroupLayout(layout_thongtin);
        layout_thongtin.setLayout(layout_thongtinLayout);
        layout_thongtinLayout.setHorizontalGroup(
            layout_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout_thongtinLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(lbl_MaVe)
                .addGap(6, 6, 6)
                .addComponent(txt_MaVe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(lbl_MaKH)
                .addGap(6, 6, 6)
                .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_NgayDI)
                .addGap(6, 6, 6)
                .addComponent(txt_NgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout_thongtinLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lbl_MaChuyenTau)
                .addGap(6, 6, 6)
                .addComponent(txt_MaChuyenTau, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addComponent(lbl_LoaiVe)
                .addGap(6, 6, 6)
                .addComponent(cbb_LoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_NgayVe)
                .addGap(6, 6, 6)
                .addComponent(txt_NgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout_thongtinLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbl_MaNV)
                .addGap(6, 6, 6)
                .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(lbl_TenVe)
                .addGap(6, 6, 6)
                .addComponent(txt_TenVe, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout_thongtinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        layout_thongtinLayout.setVerticalGroup(
            layout_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout_thongtinLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_MaVe)
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_MaVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl_MaKH))
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txt_MaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl_NgayDI))
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_NgayDi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(layout_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_MaChuyenTau)
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txt_MaChuyenTau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(lbl_LoaiVe))
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(cbb_LoaiVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_NgayVe)
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_NgayVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(layout_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TenVe)
                    .addGroup(layout_thongtinLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txt_TenVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout_thongtinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Them, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã vé", "Tên vé", "Loại vé", "Ngày đi", "Ngày đến", "Mã khách hàng", "Mã nhân viên", "Mã chuyến tàu"
            }
        ));
        tbl_DSNV.setViewportView(jTable1);

        javax.swing.GroupLayout layout_tableLayout = new javax.swing.GroupLayout(layout_table);
        layout_table.setLayout(layout_tableLayout);
        layout_tableLayout.setHorizontalGroup(
            layout_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbl_DSNV, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout_tableLayout.setVerticalGroup(
            layout_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout_tableLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tbl_DSNV, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layout_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(layout_thongtin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(lbl_Header)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Header, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layout_thongtin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(layout_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
         try {
    Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
    conn = DriverManager.getConnection(url,username,password);  
    pst = conn.prepareStatement("INSERT INTO dbo.Ve (MaVe, TenVe, LoaiVe, NgayDi, NgayVe, MaKH, MaNV, MaChuyenTau) VALUES(?,?,?,?,?,?,?,?)");
    txt_MaNV.setText(""); 
    pst.setString(1, txt_MaVe.getText());
    pst.setString(2, txt_TenVe.getText());
    pst.setString(3, (String) cbb_LoaiVe.getSelectedItem());
    pst.setString(4, txt_NgayDi.getText());
    pst.setString(5, txt_NgayVe.getText());
    pst.setString(6, txt_MaKH.getText());
    pst.setString(7, txt_MaNV.getText());
    pst.setString(8, txt_MaChuyenTau.getText());
    
    pst.executeUpdate();
    JOptionPane.showMessageDialog(this, "Thêm thành công");
    SuaDB();
} catch (SQLException ex) {
    if (ex.getSQLState().equals("23000")) {
        JOptionPane.showMessageDialog(this, "Data already exists");
    } else {
        java.util.logging.Logger.getLogger(ThongTinTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
} catch (ClassNotFoundException ex) {
    java.util.logging.Logger.getLogger(ThongTinTau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
      
   
    }//GEN-LAST:event_btn_SuaActionPerformed
    
    private void cbb_LoaiVeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_LoaiVeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_LoaiVeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_print;
    private javax.swing.JComboBox<String> cbb_LoaiVe;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel layout_table;
    private javax.swing.JPanel layout_thongtin;
    private javax.swing.JLabel lbl_Header;
    private javax.swing.JLabel lbl_LoaiVe;
    private javax.swing.JLabel lbl_MaChuyenTau;
    private javax.swing.JLabel lbl_MaKH;
    private javax.swing.JLabel lbl_MaNV;
    private javax.swing.JLabel lbl_MaVe;
    private javax.swing.JLabel lbl_NgayDI;
    private javax.swing.JLabel lbl_NgayVe;
    private javax.swing.JLabel lbl_TenVe;
    private javax.swing.JScrollPane tbl_DSNV;
    private javax.swing.JTextField txt_MaChuyenTau;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_MaVe;
    private javax.swing.JTextField txt_NgayDi;
    private javax.swing.JTextField txt_NgayVe;
    private javax.swing.JTextField txt_TenVe;
    // End of variables declaration//GEN-END:variables


}
